### ISSUE TITLE
[How To] Internal Sega Saturn Instal

### ISSUE THREAD

**Issue by maniaco007** [nostalgic-indulgences/BlueRetro_Internal_Installation#2]
Greetings from Brazil!
Excellent project, congratulations!

I recently acquired a bluetooth kit for the sega saturn, but I still haven't found anyone who has created an installation tutorial internally on the console! When I can take the time and create, I will be greatly grateful!

**Comment by nostalgic-indulgences** [comment]
Apologize for the late response, didn't realize there was a comment. Unfortunately, due to the inherent nature of the Saturn controller implementation, Stage II internal installation with port detection is not stable due to sporadic power draw of the controllers resulting in inconsistent bluetooth connections i.e. random disconnects. I was not able to stabilize the current draw by means of inline inductors and/or including decoupling capacitors. So unfortunately, the Saturn internal install is a no go at the moment. However, if you don't care about the physical controllers, Stage I implementation is possible. i.e. either use the bluetooth controller OR the physical one BUT NOT both at the same time.
